FROM rockylinux:9.3

ARG PYTHON_VERSION=3.12

WORKDIR /app

RUN dnf install -y epel-release \
        && dnf install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-pip git procps-ng lsof telnet screen iputils nmap-ncat \
        && dnf clean all \
        && update-alternatives --install /usr/bin/python python /usr/bin/python${PYTHON_VERSION} 1000 --slave /usr/bin/pip pip /usr/bin/pip${PYTHON_VERSION}

RUN pip install \
        'uv>=0.8.5' \
        'mcpo>=0.0.17' \
        'fastmcp>=2.12.4' \
        'aiohttp>=3.12.0' \
        'openstacksdk>=4.1.0,<=4.9.0' \
        'PyMySQL>=1.1.1' \
        'python-dotenv>=1.1.1'

COPY src /app/src
COPY scripts /app/scripts

CMD ["/bin/bash", "/app/scripts/mcp-server-docker-cmd.sh"]
