services:
  mcp-server:
    env_file: .env
    image: vcr.infiniband.vn/openstack.custom/mcpo-server-openstack-ops:latest
    pull_policy: always
    container_name: mcp-openstack-hcm-ops03-mcp-server
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCP_SERVER}:8000"
    volumes:
      - ./.env:/app/.env:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8000 && sleep 5"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  mcpo-proxy:
    env_file: .env
    image: vcr.infiniband.vn/openstack.custom/mcpo-proxy-openstack-ops:latest
    pull_policy: always
    container_name: mcp-openstack-hcm-ops03-mcpo-proxy
    depends_on:
      mcp-server:
        condition: service_healthy
    ports:
      - "${DOCKER_EXTERNAL_PORT_MCPO_PROXY}:8000"
    volumes:
      - ./mcp-config.json.http:/app/config/mcp-config.json
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
