[project]
name = "mcp-openstack-ops"
version = "0.0.0"
description = "OpenStack operations automation MCP server"
readme = "README.md"
requires-python = ">=3.12"
authors = [{ name = "JungJungIn", email = "call518@gmail.com" }]
dependencies = [
    "fastmcp>=2.12.3",
    "openstacksdk>=4.1.0,<=4.10.0",
    "PyMySQL>=1.1.1",
    "python-dotenv>=1.1.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0"
]

[project.scripts]
mcp-openstack-ops = "mcp_openstack_ops.mcp_main:main"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"
